name: Build & Publish to npm

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/npm.yml'
      
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js & Authenticate
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@galihridhoutomo'
          always-auth: true

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/ --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

